### ISSUE TITLE
How to change the theme?

### ISSUE THREAD

**Issue by SidorovX86** [DevExpress/dx-election#16]
Hello,

I'm developing SPA app with angular CLI and Devextreme like this one. I want my default and only one theme to be dark. What should I do to achieve this?

This solution is not working because Angular CLI:
`import DxThemes from 'devextreme/ui/themes';
DxThemes.current("generic.dark");`

May be I should directly set some styles to body or somethig like that?

What is one right solution?

Thanks.

**Comment by babich-a** [comment]
Hi
The right solution for this application is to set the right theme CSS file in the https://github.com/DevExpress/dx-election/blob/master/angular-cli.json (instead of "../node_modules/devextreme/dist/css/dx.light.css"). You can get the list of available themes here: [Predefined Themes](https://js.devexpress.com/Documentation/16_2/Guide/Themes/Predefined_Themes/).

**Comment by SidorovX86** [comment]
Thanks It works.
